### PR TITLE
feat(session): implement settings mock up

### PR DESCRIPTION
**Pull request by BeierKevin**
# PR description
*Describe your changes in detail here*

The Mock-Up from #85 has been implemented. But also gave it a little thought if the design could be changed a bit, look comments below for that.

# Definition Of Done (DoD)
*This PR can be squashed / merged if*
- [x] a developer is assigned
- [x] the PR is NOT estimated
- [x] the PR is labeled
- [x] the PR is NOT assigned to the current sprint
- [x] a meaningful title has been set according to https://www.conventionalcommits.org/
- [x] the PR is described in detail
- [x] the PR links to an issue
- [ ] the PR has been reviewed

*Add additional conditions here if necessary for this PR*

Fix: #94

### CODE REVIEW

**Comment by BeierKevin** [comment]
While implementing the Mock-Up I noticed something and thought why don't do it like the following, looks cleaner imo.

image

**Comment by Claiyc** [comment]
> While implementing the Mock-Up I noticed something and thought why don't do it like the following, looks cleaner imo.
> 
> image

like it

**Comment by BeierKevin** [comment]
Alright, I have implemented the newly discussed design iteration on top of the old design and documented in the wiki (https://github.com/VisualGameData/VIGAD/wiki/Create-Session).

**Review by Claiyc — DISMISSED** [review]
lgtm, however token generation & manual editing should be in a seperate issue

**Comment by BeierKevin** [comment]
> lgtm, however token generation & manual editing should be in a seperate issue

Yes this should be done in another issue, that's why I just added a placeholder token to showcase the input field functionality

**Review by Claiyc — APPROVED** [review]
lgtm. See #118 for additional work

**Pull request merged**
