### PR TITLE
feat: set default preview when stream can't be found anymore

### PR DESCRIPTION
**Pull request by BeierKevin**
# PR description
*Describe your changes in detail here*

If you have a program like Notepad or any other application open and selected for preview, when you close the Notepad application, the stream handler will react to it by fetching the capturable sources again and setting the main screen as the default preview. If you close Notepad and it is not the current preview, it will only trigger a refetch for the sources, ensuring that the sources tab with screens and applications is always up to date.

However, this does not happen when you open an application. I believe it is not possible with Electron to trigger a refetch automatically when opening an application. In such cases, you can simply press the refresh button, which does the job and should be sufficient.

Additionally, I added workspace settings which we should have done probably a lot earlier, which formats the code on save for everyone should be enabled per person. This was not part for this issue but noticed it and thought why not just add it.

# Definition Of Done (DoD)
*This PR can be squashed / merged if*
- [x] a developer is assigned
- [x] the PR is NOT estimated
- [x] the PR is labeled
- [x] the PR is NOT assigned to the current sprint
- [x] a meaningful title has been set according to https://www.conventionalcommits.org/
- [x] the PR is described in detail
- [x] the PR links to an issue
- [ ] the PR has been reviewed

*Add additional conditions here if necessary for this PR*

fix: #71

### CODE REVIEW

**Comment by BeierKevin** [comment]
I think this implementation satisfies what the issue #71 suggests but it would be possible to rewrite the streamhandler like a composable and utilise Vue related functionalities like watching etc. to improve performance and the user experience with everything. Could be a harder issue to tackle, tho.

**Review by Claiyc — CHANGES_REQUESTED** [review]

**Comment by BeierKevin** [comment]
Huh I did not have these issues or at least didn't try that much out, but is this related to this implementation really or was this already before ?

**Comment by Claiyc** [comment]
> Huh I did not have these issues or at least didn't try that much out, but is this related to this implementation really or was this already before ?

It was an issue before already

**Comment by Claiyc** [comment]
Please resolve conflicts before next review

**Comment by BeierKevin** [comment]
> > Huh I did not have these issues or at least didn't try that much out, but is this related to this implementation really or was this already before ?
> 
> It was an issue before already

Ahh ok

**Review by Claiyc — APPROVED** [review]
lgtm

**Pull request merged**
